// scripts/check-nav.mjs: the built sidebar is sound. It must fail on the sidebar v1.3.10 shipped
// (empty autogenerated groups) and pass on a sound one.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { checkSite, mainNav, readNav } from '../../scripts/check-nav.mjs';

const here = path.dirname(new URL(import.meta.url).pathname);

test('the v1.3.10 sidebar fails: its autogenerated groups are empty', () => {
  const nav = mainNav(readFileSync(path.join(here, 'fixtures/nav-v1.3.10-home.html'), 'utf8'));
  const { problems } = readNav(nav);
  for (const g of ['Start here', 'Scripture 101', 'Learning paths', 'Exercises', 'Architecture', 'Search & verification', 'Brand']) {
    assert.ok(problems.includes(`the sidebar group "${g}" has no links`), `reports the empty "${g}" group`);
  }
  // …and the full-sentence API operation labels
  assert.ok(problems.some((p) => /label ".*" is longer than 48/.test(p)));
});

test('a sound sidebar passes; nested groups count their children\'s links', () => {
  const nav = `<nav aria-label="Main"><ul><li><details open><summary><span>Guide</span></summary><ul>
    <li><details><summary><span>Inner</span></summary><ul><li><a href="/g/a/"><span>A page</span></a></li></ul></details></li>
    </ul></details></li></ul></nav>`;
  const { links, problems } = readNav(nav);
  assert.deepEqual(problems, []);
  assert.deepEqual(links.map((l) => l.href), ['/g/a/']);
});

test('labels shaped like a directory name, or empty, are reported; a badge is not part of the label', () => {
  const nav = `<nav aria-label="Main"><details><summary><span>runbooks</span></summary>
    <a href="/x/"><span>Deploys</span> <span class="sl-badge">sggs-data</span></a></details></nav>`;
  const { links, problems } = readNav(nav);
  assert.equal(links[0].label, 'Deploys');
  assert.deepEqual(problems, ['the sidebar group label "runbooks" looks like a raw directory name']);
});

/** A tiny built site: pages { '/a/': { nav, prev, next } } plus its sitemap. */
function fakeDist(pages) {
  const dist = mkdtempSync(path.join(tmpdir(), 'dist-'));
  const url = (p) => `https://docs.example${p}`;
  writeFileSync(path.join(dist, 'sitemap-index.xml'), `<sitemapindex><sitemap><loc>${url('/sitemap-0.xml')}</loc></sitemap></sitemapindex>`);
  writeFileSync(path.join(dist, 'sitemap-0.xml'), `<urlset>${['/', ...Object.keys(pages)].map((p) => `<url><loc>${url(p)}</loc></url>`).join('')}</urlset>`);
  const all = Object.keys(pages);
  for (const [p, o] of Object.entries(pages)) {
    const links = (o.links ?? all).map((h) => `<li><a href="${h}"${h === p ? ' aria-current="page"' : ''}><span>${o.rename?.[h] ?? `Page ${h}`}</span></a></li>`).join('');
    const nav = `<nav aria-label="Main"><details open><summary><span>Group</span></summary><ul>${links}</ul></details></nav>`;
    const pag = `<div class="pagination-links">${o.prev ? '<a rel="prev" href="#">p</a>' : ''}${o.next ? '<a rel="next" href="#">n</a>' : ''}</div>`;
    mkdirSync(path.join(dist, p), { recursive: true });
    writeFileSync(path.join(dist, p, 'index.html'), `<html><body>${nav}<main></main>${pag}</body></html>`);
  }
  return dist;
}

test('a site where every page is linked, current and paginated passes', () => {
  const dist = fakeDist({ '/a/': { next: true }, '/b/': { prev: true, next: true }, '/c/': { prev: true } });
  assert.deepEqual(checkSite(dist, { exempt: {} }), []);
});

test('a page missing from the sidebar, or without previous/next, fails', () => {
  const dist = fakeDist({
    '/a/': { next: true, links: ['/a/', '/b/'] },
    '/b/': { prev: true, links: ['/a/', '/b/'] },
    '/c/': { prev: true, links: ['/a/', '/b/', '/c/'] },   // only reachable from itself
  });
  const problems = checkSite(dist, { exempt: {} });
  assert.ok(problems.includes('/c/: published but not in the sidebar (place it in docs-site/sidebar.mjs, or list it in NAV_EXEMPT with a reason)'));

  const dist2 = fakeDist({ '/a/': { next: true }, '/b/': { next: true }, '/c/': { prev: true } });
  assert.ok(checkSite(dist2, { exempt: {} }).includes('/b/: no "Previous" link'));
});

test('a sidebar entry renamed on one page fails (pagination must never rename the sidebar)', () => {
  const dist = fakeDist({ '/a/': { next: true }, '/b/': { prev: true, next: true, rename: { '/a/': 'Section overview' } }, '/c/': { prev: true } });
  assert.deepEqual(checkSite(dist, { exempt: {} }), ['/b/: the sidebar labels /a/ "Section overview" here but "Page /a/" on /a/']);
});
