// The sidebar, built from the pages that exist.
//
// Starlight's `autogenerate` matches a page by its file path relative to src/content/docs. This
// site reads ../docs (and the pinned sibling docs) in place (src/content.config.ts), so nothing
// ever matched: every autogenerated group rendered as an empty, open <details> — and Starlight does
// not refuse an empty group. So the sidebar is built here, at config time, from explicit `slug`
// items only: Starlight fails the build on a slug with no page, which is the safety net we want.
//
// The layout (which pages go in which group) is declared in ../sidebar.mjs with the helpers below;
// buildSidebar() resolves it against the pages found on disk and throws on anything inconsistent:
// an empty group, a page placed twice, a page placed nowhere (tested in plugins/test/sidebar.test.mjs).
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { parseFrontmatter } from '@astrojs/markdown-remark';
import { REPO_ROOT, SOURCES_DIR, idForRepoPath, loadSources } from './paths.mjs';

export const LABEL_MAX = 48;

/** Every published page: id -> { id, repoPath, source (sibling name or null), title, label, order, isIndex }. */
export function readPages({ root = REPO_ROOT, sources = loadSources(), warn = console.warn } = {}) {
  const pages = new Map();
  const missingSources = new Set();
  const add = (repoPath, source) => {
    const id = idForRepoPath(repoPath, sources);
    if (!id || id === 'index') return;               // unpublished, or the home page (not in the sidebar)
    const fm = parseFrontmatter(readFileSync(path.join(root, repoPath), 'utf8')).frontmatter ?? {};
    if (fm.draft === true || fm.sidebar?.hidden === true) return;
    if (pages.has(id)) throw new Error(`sidebar: two files publish the page "${id}": ${pages.get(id).repoPath} and ${repoPath}`);
    pages.set(id, {
      id, repoPath, source,
      title: String(fm.title ?? id),
      label: fm.sidebar?.label ? String(fm.sidebar.label) : null,
      order: Number.isFinite(fm.sidebar?.order) ? fm.sidebar.order : Infinity,
    });
  };

  const walk = (dir) => {
    for (const name of readdirSync(path.join(root, dir), { withFileTypes: true })) {
      const rel = `${dir}/${name.name}`;
      if (name.isDirectory()) walk(rel);
      else if (name.name.endsWith('.md')) add(rel, null);
    }
  };
  walk('docs');

  // pinned sibling docs: exactly the Markdown files the lock pins, once installed by
  // tools/fetch_sibling_docs.py (CI always installs first; a bare local `npm` run may not have)
  for (const [name, src] of Object.entries(sources)) {
    const base = `${SOURCES_DIR}/${name}`;
    if (!existsSync(path.join(root, base, '.installed.json'))) {
      missingSources.add(name);
      warn(`sidebar: ${name} docs are not installed — run python3 tools/fetch_sibling_docs.py; its pages are left out`);
      continue;
    }
    for (const rel of Object.keys(src.files ?? {}).sort()) {
      if (rel.endsWith('.md') && existsSync(path.join(root, base, rel))) add(`${base}/${rel}`, name);
    }
  }

  // a directory's index is the page whose id is the directory's own id (docs/<dir>/README.md)
  const ids = new Set(pages.keys());
  for (const p of pages.values()) p.isIndex = [...ids].some((other) => other.startsWith(p.id + '/'));
  return { pages, missingSources };
}

// ----------------------------------------------------------------------------- layout helpers
/** A group of items (pages() / page() / group()). */
export const group = (label, items, { collapsed = true } = {}) => ({ kind: 'group', label, items, collapsed });
/** One page by id. `from` names the sibling source for a pinned page. */
export const page = (id, { from = null, label } = {}) => ({ kind: 'page', id, from, label });
/** The pages directly inside a directory (its index first), from this repository or a pinned source. */
export const pages = (dir, { from = null, exclude = [], index = true } = {}) => ({ kind: 'dir', dir, from, exclude, index });

const directChild = (id, dir) => id.startsWith(dir + '/') && !id.slice(dir.length + 1).includes('/');
const byOrder = (a, b) => (a.order - b.order) || a.title.localeCompare(b.title);

/**
 * Resolve the layout against the pages on disk into Starlight sidebar config.
 * @param spec layout from ../sidebar.mjs
 * @param opts.labels   id -> sidebar label (overrides a page's title; short labels for long titles)
 * @param opts.badges   sibling source name -> Starlight badge for its pages
 * @param opts.order    id -> sort order, over the page's frontmatter `sidebar.order` (pinned pages carry none)
 */
export function buildSidebar(spec, { pages: all, missingSources = new Set() }, { labels = {}, badges = {}, order = {} } = {}) {
  const placed = new Map();   // id -> group path, to refuse a page placed twice

  const linkFor = (p, where, label) => {
    if (placed.has(p.id)) throw new Error(`sidebar: "${p.id}" is placed twice (${placed.get(p.id)} and ${where})`);
    placed.set(p.id, where);
    const item = { label: label ?? labels[p.id] ?? p.label ?? (p.isIndex ? 'Overview' : p.title), slug: p.id };
    if (p.source && badges[p.source]) item.badge = badges[p.source];
    return item;
  };

  const resolve = (node, where) => {
    if (node.kind === 'page') {
      const p = all.get(node.id);
      if (!p) {
        if (node.from && missingSources.has(node.from)) return [];
        throw new Error(`sidebar: no published page "${node.id}" (in ${where})`);
      }
      if ((p.source ?? null) !== (node.from ?? null)) throw new Error(`sidebar: "${node.id}" comes from ${p.source ?? 'this repository'}, not ${node.from ?? 'this repository'}`);
      return [linkFor(p, where, node.label)];
    }
    if (node.kind === 'dir') {
      if (node.from && missingSources.has(node.from)) return [];
      const inDir = [...all.values()].filter((p) => (p.source ?? null) === (node.from ?? null) && !node.exclude.includes(p.id));
      const idx = node.index ? inDir.find((p) => p.id === node.dir) : null;
      const kids = inDir.filter((p) => directChild(p.id, node.dir))
        .map((p) => ({ ...p, order: order[p.id] ?? p.order }))
        .sort(byOrder);
      const found = [...(idx ? [idx] : []), ...kids];
      if (!found.length) throw new Error(`sidebar: no pages in ${node.from ? `${node.from}:` : ''}${node.dir} (in ${where})`);
      return found.map((p) => linkFor(p, where));
    }
    // group
    const here = where ? `${where} › ${node.label}` : node.label;
    const items = node.items.flatMap((n) => resolve(n, here));
    if (!items.length) {
      // a group made only of a missing sibling source's pages is dropped (local builds without the fetch)
      const onlyMissing = node.items.every((n) => n.from && missingSources.has(n.from));
      if (onlyMissing) return [];
      throw new Error(`sidebar: the group "${here}" is empty`);
    }
    return [{ label: node.label, collapsed: node.collapsed, items }];
  };

  const sidebar = spec.flatMap((n) => resolve(n, ''));
  const unplaced = [...all.keys()].filter((id) => !placed.has(id));
  if (unplaced.length) throw new Error(`sidebar: published pages placed in no group: ${unplaced.join(', ')} — add them to docs-site/sidebar.mjs`);
  return sidebar;
}

/** Every link in a built sidebar, depth-first, with the labels of the groups above it. */
export function* sidebarLinks(items, trail = []) {
  for (const it of items) {
    if (it.items) yield* sidebarLinks(it.items, [...trail, it.label]);
    else yield { ...it, trail };
  }
}
