// After a build: every page can be reached from the sidebar, and the sidebar is sound. This reads
// the built HTML — what a reader sees — so it catches what a config-level test cannot: for a whole
// release every autogenerated group rendered as an empty, open <details> and 87 pages could only be
// found through search, while every other check stayed green.
//
//   node scripts/check-nav.mjs [dist]
//
// On every page in the sitemap (except the home page and any listed in NAV_EXEMPT, with a reason):
//   - the main sidebar has no group without a link, and no label longer than LABEL_MAX or shaped like
//     a raw directory name ("runbooks");
//   - the sidebar links to every expected page, and marks exactly this page aria-current;
//   - the sidebar is the same on every page (same links, same labels) — so a page's own data can
//     never rename a sidebar entry;
//   - the page has previous and next links (the first and last page in sidebar order excepted).
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { LABEL_MAX } from '../plugins/nav.mjs';

// Pages published but deliberately not in the sidebar: path -> why. Keep it short.
export const NAV_EXEMPT = {
  '/404/': 'the not-found page',
};

const RAW_DIR = /^[a-z0-9-]+$/;
const text = (html) => html.replace(/<[^>]+>/g, ' ').replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();

/** The main sidebar's HTML in a page, or null. */
export function mainNav(html) {
  const start = html.search(/<nav[^>]*aria-label="Main"/);
  if (start < 0) return null;
  const end = html.indexOf('</nav>', start);
  return html.slice(start, end < 0 ? undefined : end);
}

/**
 * Walk a sidebar's markup: its links (in order) and its problems (empty groups, bad labels).
 * @returns {{ links: {href:string, label:string, current:boolean}[], problems: string[] }}
 */
export function readNav(nav) {
  const links = [];
  const problems = [];
  const stack = [];   // open <details>: { label, links }
  const tokens = /<details\b[^>]*>|<\/details>|<summary\b[^>]*>([\s\S]*?)<\/summary>|<a\s([^>]*)>([\s\S]*?)<\/a>/g;
  for (const m of nav.matchAll(tokens)) {
    const tag = m[0];
    if (tag.startsWith('<details')) stack.push({ label: '', links: 0 });
    else if (tag === '</details>') {
      const g = stack.pop();
      if (g && g.links === 0) problems.push(`the sidebar group "${g.label}" has no links`);
      if (g && stack.length) stack[stack.length - 1].links += g.links;
    } else if (tag.startsWith('<summary')) {
      const label = text(m[1]);
      if (stack.length) stack[stack.length - 1].label = label;
      checkLabel(label, 'group', problems);
    } else {
      const attrs = m[2];
      const href = /href="([^"]+)"/.exec(attrs)?.[1];
      if (!href || !href.startsWith('/')) continue;   // external links (GitHub) are not pages
      // the label is the first <span>; a badge ("sggs-data", "GET") follows it
      const label = text(/<span[^>]*>([\s\S]*?)<\/span>/.exec(m[3])?.[1] ?? m[3]);
      links.push({ href, label, current: /aria-current="page"/.test(attrs) });
      checkLabel(label, 'link', problems);
      if (stack.length) stack[stack.length - 1].links += 1;
    }
  }
  return { links, problems };
}

function checkLabel(label, kind, problems) {
  if (!label) problems.push(`a sidebar ${kind} has no label`);
  else if (label.length > LABEL_MAX) problems.push(`the sidebar ${kind} label "${label}" is longer than ${LABEL_MAX} characters`);
  else if (RAW_DIR.test(label)) problems.push(`the sidebar ${kind} label "${label}" looks like a raw directory name`);
}

/** The site paths listed in the sitemap. */
export function sitemapPaths(dist) {
  const index = path.join(dist, 'sitemap-index.xml');
  const files = existsSync(index)
    ? [...readFileSync(index, 'utf8').matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => path.join(dist, path.basename(new URL(m[1]).pathname)))
    : [];
  return files.flatMap((f) => [...readFileSync(f, 'utf8').matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => new URL(m[1]).pathname));
}

const pageFile = (dist, p) => path.join(dist, p, 'index.html');

/** Check a built site; returns the list of problems (empty = sound). */
export function checkSite(dist, { exempt = NAV_EXEMPT } = {}) {
  const problems = [];
  const expected = sitemapPaths(dist).filter((p) => p !== '/' && !(p in exempt));
  if (!expected.length) return [`no pages found in ${dist}/sitemap-index.xml — build first`];

  let order = null;   // the sidebar's link order, from the first page (the same on every page)
  let labels = null;  // href -> label, from the first page
  for (const p of expected) {
    const file = pageFile(dist, p);
    if (!existsSync(file)) { problems.push(`${p}: in the sitemap but not built`); continue; }
    const html = readFileSync(file, 'utf8');
    const nav = mainNav(html);
    if (!nav) { problems.push(`${p}: no sidebar`); continue; }
    const { links, problems: navProblems } = readNav(nav);
    for (const q of navProblems) problems.push(`${p}: ${q}`);
    if (!order) {
      order = links.map((l) => l.href);
      labels = new Map(links.map((l) => [l.href, l.label]));
      const inNav = new Set(order);
      for (const e of expected) if (!inNav.has(e)) problems.push(`${e}: published but not in the sidebar (place it in docs-site/sidebar.mjs, or list it in NAV_EXEMPT with a reason)`);
      for (const l of new Set(order)) if (order.indexOf(l) !== order.lastIndexOf(l)) problems.push(`${l}: in the sidebar twice`);
    }
    else {
      if (links.length !== order.length) problems.push(`${p}: the sidebar has ${links.length} links here but ${order.length} on ${expected[0]}`);
      for (const l of links) if (labels.has(l.href) && labels.get(l.href) !== l.label) problems.push(`${p}: the sidebar labels ${l.href} "${l.label}" here but "${labels.get(l.href)}" on ${expected[0]}`);
    }
    const current = links.filter((l) => l.current).map((l) => l.href);
    if (current.length !== 1 || current[0] !== p) problems.push(`${p}: the sidebar marks ${current.length ? current.join(', ') : 'nothing'} as the current page`);

    const at = order.indexOf(p);
    const pag = html.slice(html.indexOf('pagination-links'));
    if (at > 0 && !/rel="prev"/.test(pag)) problems.push(`${p}: no "Previous" link`);
    if (at >= 0 && at < order.length - 1 && !/rel="next"/.test(pag)) problems.push(`${p}: no "Next" link`);
  }
  return problems;
}

function main() {
  const dist = path.resolve(process.argv[2] ?? 'dist');
  const problems = checkSite(dist);
  const pages = sitemapPaths(dist).length;
  if (problems.length) {
    for (const p of problems.slice(0, 60)) console.error(`::error::check-nav: ${p}`);
    if (problems.length > 60) console.error(`… and ${problems.length - 60} more`);
    console.error(`check-nav: ${problems.length} problem(s) across ${pages} pages`);
    process.exit(1);
  }
  console.log(`check-nav: ${pages} pages — every page is in the sidebar, no empty group, previous/next everywhere`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) main();
