#!/usr/bin/env python3
"""Generate docs/api/errors.md — every error the API returns, as the server really answers it.

    python3 tools/gen_api_errors.py            # rewrite docs/api/errors.md
    python3 tools/gen_api_errors.py --check    # exit 1 if the committed page differs (CI)

Starts webapp/serve.py's handler in process on a free local port, sends each case in CASES to
both surfaces (/api and /api/v1) with a fixed X-Request-Id, and writes the status and body it
gets back. Nothing on the page is typed by hand except the case list and the prose around it, so
a changed message, status or envelope shows up as drift. Bodies are summarised (lists become
their length) and the page must contain no Gurmukhi. Stdlib only; needs the pinned database
(make dataset).
"""
from __future__ import annotations

import json
import os
import sys
import threading
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "db" / "sggs.sqlite"
OUT = ROOT / "docs" / "api" / "errors.md"
HEADER = "<!-- generated by tools/gen_api_errors.py by calling the API in process — do not edit; run the generator -->"
RID = "example-request-0001"

# (request as shown, request as sent, why a client would hit it)
ERRORS = [
    ("/api/nope", "/api/nope", "a path that is not a route"),
    ("/api/ang", "/api/ang", "a route that needs an id, without one"),
    ("/api/ang/abc", "/api/ang/abc", "an id that is not an integer"),
    ("/api/ang/1234567890123", "/api/ang/1234567890123", "an integer longer than 12 characters"),
    ("/api/search?q=naam&limit=abc", "/api/search?q=naam&limit=abc", "an integer parameter that is not an integer"),
    ("/api/shabad/1", "/api/shabad/1", "a `comp_id` that is a permanent gap"),
    ("/api/shabad/99999999", "/api/shabad/99999999", "a `comp_id` beyond the last composition"),
    ("/api/search?q=‹301 characters›", "/api/search?q=" + "a" * 301, "a search query over 300 characters"),
    ("/api/verify?q=", "/api/verify?q=", "an empty claim"),
    ("/api/verify?q=‹601 characters›", "/api/verify?q=" + "a" * 601, "a claim over 600 characters"),
    ("/api/bani", "/api/bani", "a bani without its key"),
    ("/api/bani/NOPE!", "/api/bani/NOPE!", "a key with characters a key never has"),
    ("/api/bani/nope", "/api/bani/nope", "a well-formed key that is not a bani"),
    ("/api/bani/japji?variant=zz", "/api/bani/japji?variant=zz", "a variant that is not one of the bani's"),
    ("/api/analytics/progression", "/api/analytics/progression", "progression without `raag`"),
    ("/api/timing/raag", "/api/timing/raag", "a raag lookup without `name`"),
    ("/api/forms?comp_id=0", "/api/forms?comp_id=0", "forms without a usable `comp_id`"),
]

# Requests a client might expect to fail that succeed: clamped, or empty.
NOT_ERRORS = [
    ("/api/ang/0", "an Ang below 1 is clamped to 1"),
    ("/api/ang/1431", "an Ang above 1430 is clamped to 1430"),
    ("/api/search?q=naam&limit=999", "`limit` above 200 is clamped to 200"),
    ("/api/lines?ids=abc", "ids that are not digits are ignored"),
    ("/api/analytics/vaar?id=x", "a Vaar id that is not a number finds no Vaar"),
    ("/api/word", "no word: nothing to count"),
    ("/api/neighbors", "no `line_id`: no neighbours"),
    ("/api/timing/raag?name=nope", "an unknown raag name: no claims"),
]


def _serve():
    os.environ.setdefault("SGGS_ACCESS_LOG", "0")
    sys.path.insert(0, str(ROOT / "webapp"))
    import serve  # noqa: E402
    from http.server import ThreadingHTTPServer
    srv = ThreadingHTTPServer(("127.0.0.1", 0), serve.H)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv


def _get(port: int, path: str) -> tuple[int, dict]:
    req = urllib.request.Request(f"http://127.0.0.1:{port}{path}", headers={"X-Request-Id": RID})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.status, json.loads(r.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


def _summary(body) -> str:
    """Top-level JSON with lists reduced to their length, Gurmukhi replaced by a marker, long strings shortened."""
    def s(v):
        if isinstance(v, list):
            return f"[{len(v)} item{'s' if len(v) != 1 else ''}]"
        if isinstance(v, dict):
            return "{…}"
        if isinstance(v, str) and any("\u0a00" <= ch <= "\u0a7f" for ch in v):
            return "‹Gurmukhi›"
        if isinstance(v, str) and len(v) > 48:
            return v[:45] + "…"
        return v
    def r(v):
        m = s(v)
        marker = isinstance(v, (list, dict)) or m == "‹Gurmukhi›"
        return m if marker else json.dumps(m, ensure_ascii=False)
    return "{" + ", ".join(f"{json.dumps(k)}: {r(v)}" for k, v in body.items()) + "}"


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render(get) -> str:
    out = [
        "---",
        'title: "Error reference"',
        'description: "Every error the API returns — status, legacy body and /api/v1 envelope — generated by calling the server, plus the requests that are clamped or empty instead."',
        "sidebar:",
        "  order: 4",
        "---",
        HEADER,
        "# Error reference",
        "",
        "Every error below was produced by calling the server's own handler, on both surfaces, when this page was",
        "generated; CI regenerates it and fails if a status, a message or an envelope has changed. A client should",
        "branch on the **status** (and, on `/api/v1`, the `code`), never on the message text.",
        "",
        "## The two shapes",
        "",
        "| | `/api/…` (legacy) | `/api/v1/…` |",
        "|---|---|---|",
        '| Bad parameter | `400`, `{"error": "invalid request: <message>"}` | `400`, `{"error": {"code": "invalid_request", "message", "request_id"}}` |',
        '| Not found (a gap, an unknown bani) | `404`, `{"error": "<message>"}` | `404`, code `not_found` |',
        '| Unknown endpoint | `400`, `{"error": "invalid request: unknown endpoint"}` | `404`, code `not_found` |',
        '| Unexpected failure | `500`, `{"error": "internal server error"}` | `500`, code `internal`, message `internal server error` |',
        "",
        "The legacy shape is frozen: the golden contract and the app depend on it byte for byte. New clients should",
        "use `/api/v1`, whose `request_id` is the same id as the `X-Request-Id` header and the access log",
        "([versioning and caching](versioning-and-caching.md)). A `500` never carries the exception; the detail is",
        "only in the server log, under that request id.",
        "",
        "## Every error, as the server answers it",
        "",
        "| Request | When | Status | Legacy body | `/api/v1` code · message |",
        "|---|---|--:|---|---|",
    ]
    for shown, sent, why in ERRORS:
        st, legacy = get(sent)
        st1, v1 = get(sent.replace("/api/", "/api/v1/", 1))
        if st < 400 or st1 < 400:
            raise SystemExit(f"gen_api_errors: {sent} no longer fails ({st}, {st1}) — move it to NOT_ERRORS or drop it")
        e = v1["error"]
        if e.get("request_id") != RID:
            raise SystemExit(f"gen_api_errors: {sent}: the v1 envelope did not echo the request id")
        status = f"{st}" if st == st1 else f"{st} · v1 {st1}"
        out.append(f"| `{_cell(shown)}` | {why} | {status} | `{_cell(json.dumps(legacy, ensure_ascii=False))}` "
                   f"| `{e['code']}` · {_cell(e['message'])} |")
    out += [
        "",
        "## Not errors",
        "",
        "Most parameters are clamped to their range rather than rejected, and some malformed input simply finds",
        "nothing. These requests all return `200`; check the body, not only the status:",
        "",
        "| Request | What happens | Status | Body (lists shown as their length, Gurmukhi as ‹Gurmukhi›) |",
        "|---|---|--:|---|",
    ]
    for path, why in NOT_ERRORS:
        st, body = get(path)
        if st != 200:
            raise SystemExit(f"gen_api_errors: {path} now returns {st} — move it to ERRORS")
        out.append(f"| `{_cell(path)}` | {why} | {st} | `{_cell(_summary(body))}` |")
    out += [
        "",
        "## Beyond a single request",
        "",
        "- **`404` from a single-context service.** A service that runs one context answers a route it does not",
        "  own with `404` and the message `/api/<route> is not served by this service`. Through the public origin",
        "  the gateway always sends a route to its own service, so a client only sees this when calling a function",
        "  directly ([bounded contexts and the gateway](../architecture/bounded-contexts-and-gateway.md)).",
        "- **`503` from `/readyz`.** `{\"ready\": false, …}` when a declared table is missing, or",
        "  `{\"ready\": false, \"error\": \"database unavailable\"}`. `/healthz` is liveness only.",
        "- **The platform in front.** Vercel may answer before the API does, for example a timeout or a challenge",
        "  page for an unusual burst of requests. Such responses are not JSON from this API and carry no",
        "  `X-Service` header.",
        "",
    ]
    page = "\n".join(out)
    if any("਀" <= ch <= "੿" for ch in page):
        raise SystemExit("gen_api_errors: the page would contain Gurmukhi — summarise that body instead")
    return page


def main(argv: list[str]) -> int:
    if not DB.exists():
        print(f"gen_api_errors: {DB.relative_to(ROOT)} is missing — run: make dataset", file=sys.stderr)
        return 2
    srv = _serve()
    try:
        page = render(lambda path: _get(srv.server_address[1], path))
    finally:
        srv.shutdown()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != page:
            print(f"::error file={OUT.relative_to(ROOT)}::stale — run: python3 tools/gen_api_errors.py", file=sys.stderr)
            return 1
        print(f"gen_api_errors: {OUT.relative_to(ROOT)} matches the server")
        return 0
    OUT.write_text(page)
    print(f"gen_api_errors: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
