#!/usr/bin/env python3
"""Generate docs/data/data-dictionary.md — every table in the pinned database, from the database.

    python3 tools/gen_data_dictionary.py            # rewrite docs/data/data-dictionary.md
    python3 tools/gen_data_dictionary.py --check    # exit 1 if the committed page differs (CI)

Read from three places: dataset.lock.json (which dataset is pinned), the pinned database itself
(tables, columns, row counts, the meta table) and webapp/serve.py:CONTEXT_TABLES (which bounded
context may read each table). The one thing written by hand is TABLES below: a layer and a
one-line description per table. A table in the database with no description, or a description
for a table the database does not have, fails the generation — so the page can never omit or
invent a table. FTS5 shadow tables (…_data, …_idx, …) are summarised with their index. The page
contains no Gurmukhi: a tokenizer's character list is summarised, never printed. Stdlib only;
needs the pinned database (make dataset).
"""
from __future__ import annotations

import json
import re
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "db" / "sggs.sqlite"
LOCK = ROOT / "dataset.lock.json"
OUT = ROOT / "docs" / "data" / "data-dictionary.md"
HEADER = "<!-- generated by tools/gen_data_dictionary.py from the pinned database — do not edit; run the generator -->"

LAYERS = [
    ("scripture", "Scripture and structure",
     "The verbatim text and the structure derived from it. Everything else refers to these rows."),
    ("search", "Search indexes",
     "Built from the scripture tables at rebuild time; the search and verify contexts read them."),
    ("translation", "The English translation",
     "A separate, labelled layer. It never replaces or mixes with the Gurmukhi."),
    ("banis", "Banis (Nitnem)",
     "The daily prayers as ordered references to lines, plus the few lines that come from outside the Granth."),
    ("insights", "Insights (precomputed analytics)",
     "Descriptive statistics over structure, the theme tags and the English. See [the insights context](../architecture/insights-context.md)."),
    ("knowledge", "Knowledge (timing and forms)",
     "Attributed scholarship about the text. See [the knowledge context](../architecture/knowledge-context.md)."),
    ("build", "Build records",
     "Bookkeeping written by the rebuild; no route serves it except as metadata."),
]

# table -> (layer, what it holds). Keep each description to one sentence about the table's role.
TABLES: dict[str, tuple[str, str]] = {
    "lines": ("scripture", "One row per printed line: the verbatim Gurmukhi with its Ang, raag, section, author and composition; the source of truth ([anatomy of a line record](line-record.md))."),
    "meta": ("scripture", "Facts about the build as key/value pairs: version, build date, edition, totals."),
    "raags": ("scripture", "Each raag with its Ang span, line and shabad counts, Roman name and order in the Granth."),
    "sections": ("scripture", "Each section of the Granth with its Ang span and line count."),
    "authors": ("scripture", "Each contributor with the Ang span and number of lines attributed."),
    "word_freq": ("scripture", "Every distinct Gurmukhi word and how often it occurs."),
    "fts": ("search", "Full-text index over `lines`: the text, transliteration, Roman fold, first letters and consonant skeleton."),
    "fts_tri": ("search", "Trigram index over the transliteration, for partial and misspelt Roman queries."),
    "fts_shabad": ("search", "Full-text index over each composition's Roman consonant skeleton, for queries that span lines."),
    "canon_tokens": ("search", "Every distinct token of the transliteration, used to tell a known Roman word from a misspelling."),
    "variants": ("search", "Spelling and phonetic variants, each mapped to the Gurmukhi word it stands for, with frequency, score and type."),
    "translations": ("translation", "The English translation, one row per translated line, with its source and match quality."),
    "fts_en": ("translation", "Full-text index over the English translation."),
    "sources": ("translation", "Where each translation comes from: attribution, licence terms and the date ingested."),
    "banis": ("banis", "Each bani and variant: titles, category, order, length and where it comes from."),
    "bani_lines": ("banis", "The ordered lines of each bani, each a reference to a Granth line or to an extra line."),
    "extra_lines": ("banis", "Lines of banis that are not in the Granth, with their source and review status."),
    "concepts": ("insights", "The curated themes."),
    "concept_lines": ("insights", "Which lines carry which theme."),
    "theme_network": ("insights", "Theme pairs that occur in the same shabads, with PPMI and Jaccard."),
    "theme_fingerprint": ("insights", "How strongly each author or raag carries each theme, as lift over the whole Granth."),
    "author_analytics": ("insights", "Per-author counts and stylometry of the English translation, with a reliability flag."),
    "author_distinctive_terms": ("insights", "The English terms most characteristic of each author."),
    "author_resonance": ("insights", "How often one voice's lines land nearest another's, as lift."),
    "raag_analytics": ("insights", "Per-raag counts and theme emphasis."),
    "shabad_neighbors": ("insights", "For each composition, the ten with the most similar theme profile."),
    "line_neighbors": ("insights", "For each line, the lines whose English is closest by TF-IDF cosine (0.30 and above)."),
    "vaars": ("insights", "The Vaars: span, pauri and salok counts, and who wrote each part."),
    "vaar_units": ("insights", "Each Vaar's saloks and pauris in reading order."),
    "raag_timing_claims": ("knowledge", "When each raag is sung according to a cited source: pahar, season or occasion, with confidence."),
    "timing_sources": ("knowledge", "The sources behind the timing claims and their tradition."),
    "shabd_raag_map": ("knowledge", "Each composition's raag, first Ang and first line."),
    "shabd_structural_form": ("knowledge", "A composition's form when its heading states it; otherwise NULL, never guessed."),
    "shabd_poetic_genre": ("knowledge", "A composition's named genre when its heading states it."),
    "shabd_musical_markers": ("knowledge", "Ghar, partaal, rahao and other musical markers stated in a composition's heading."),
    "analytics_meta": ("build", "How the analytics were built: methods, framing, build dates."),
    "timing_migrations": ("build", "The timing layer's applied migrations and whether the scripture baseline was verified."),
}

FTS_SHADOW = ("_config", "_content", "_data", "_docsize", "_idx")


def _tokenizer(sql: str) -> str:
    m = re.search(r"tokenize\s*=\s*[\"']([^\"']*(?:'[^']*'[^\"']*)*)[\"']", sql)
    if not m:
        return "`unicode61` (the default)"
    tok = m.group(1)
    if "tokenchars" in tok:
        n = len(re.search(r"tokenchars\s+'([^']*)'", tok).group(1))
        return f"`{tok.split()[0]}`, with {n} Gurmukhi signs counted as part of a token"
    return f"`{tok.strip()}`"


def read(db: Path, contexts: dict[str, frozenset]) -> dict:
    con = sqlite3.connect(f"file:{db}?mode=ro&immutable=1", uri=True)
    master = con.execute("SELECT name, sql FROM sqlite_master WHERE type='table' ORDER BY name").fetchall()
    virtual = {n for n, s in master if s and s.upper().startswith("CREATE VIRTUAL TABLE")}
    shadows = {n for n, _ in master for v in virtual if n.startswith(v) and n[len(v):] in FTS_SHADOW}
    tables = []
    for name, sql in master:
        if name in shadows or name.startswith("sqlite_"):
            continue
        cols = [(r[1], r[2] or "") for r in con.execute(f'PRAGMA table_info("{name}")')]
        rows = con.execute(f'SELECT COUNT(*) FROM "{name}"').fetchone()[0]
        readers = sorted(c for c, t in contexts.items() if name in t)
        tables.append({"name": name, "cols": cols, "rows": rows, "readers": readers,
                       "fts": _tokenizer(sql) if name in virtual else None})
    meta = dict(con.execute("SELECT key, value FROM meta").fetchall())
    con.close()
    return {"tables": tables, "meta": meta, "shadow_count": len(shadows)}


def render(data: dict, lock: dict, described: dict = TABLES) -> str:
    names = {t["name"] for t in data["tables"]}
    missing = sorted(names - set(described))
    extra = sorted(set(described) - names)
    if missing or extra:
        raise SystemExit("gen_data_dictionary: the descriptions and the database disagree — "
                         f"undescribed: {missing or 'none'}; described but absent: {extra or 'none'}. Edit TABLES.")
    meta, db = data["meta"], lock["database"]
    fts = [t for t in data["tables"] if t["fts"]]
    out = [
        "---",
        'title: "Data dictionary"',
        'description: "Every table in the pinned database — its layer, what it holds, its columns, its row count and which API context reads it — generated from the database itself."',
        "sidebar:",
        "  order: 3",
        "---",
        HEADER,
        "# Data dictionary",
        "",
        f"Every table in the pinned database: {len(data['tables'])} tables, of which {len(fts)} are full-text indexes"
        f" (their {data['shadow_count']} internal shadow tables are not listed). The page is generated from the database"
        " by `tools/gen_data_dictionary.py`, and CI fails if it differs from the database the platform pins, so the"
        " counts and columns below are those of the dataset in the lock.",
        "",
        "| The pinned dataset | |",
        "|---|---|",
        f"| Built by | [`{lock['repository']}`](https://github.com/{lock['repository']}) at `{lock['commit'][:8]}` |",
        f"| `DATASET_VERSION` (the lock) | `{lock['dataset_version']}` |",
        f"| Database build version (`meta.version`) | `{meta.get('version', '?')}`, built {meta.get('built', '?')} |",
        f"| SHA-256 | `{db['sha256'][:16]}…` |",
        f"| Size | {db['size'] / 1024 / 1024:.1f} MiB |",
        f"| Lines · Angs | {int(meta.get('total_lines', 0)):,} · {int(meta.get('total_angs', 0)):,} |",
        "",
        "Which version is which, and how a new dataset arrives, is on [the dataset pin](dataset-pin.md). The",
        "database is opened read-only by the API; **Read by** names the bounded contexts that declare the table",
        "(`TABLES` in each module, enforced by `webapp/tests/test_declared_tables.py`).",
        "",
    ]
    for key, title, intro in LAYERS:
        rows = [t for t in data["tables"] if described[t["name"]][0] == key]
        if not rows:
            continue
        out += [f"## {title}", "", intro, "",
                "| Table | Rows | Read by | What it holds |", "|---|--:|---|---|"]
        for t in rows:
            readers = ", ".join(t["readers"]) or "—"
            out.append(f"| [`{t['name']}`](#{t['name']}) | {t['rows']:,} | {readers} | {described[t['name']][1]} |")
        out.append("")
        for t in rows:
            out += [f"### {t['name']}", ""]
            if t["fts"]:
                out += [f"FTS5 index; tokenizer {t['fts']}.", ""]
            out += [" · ".join(f"`{c}` {typ}".rstrip() for c, typ in t["cols"]), ""]
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    sys.path.insert(0, str(ROOT / "webapp"))
    import serve  # noqa: E402  (CONTEXT_TABLES; no database is opened at import)
    if not DB.exists():
        print(f"gen_data_dictionary: {DB.relative_to(ROOT)} is missing — run: make dataset", file=sys.stderr)
        return 2
    page = render(read(DB, serve.CONTEXT_TABLES), json.loads(LOCK.read_text()))
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != page:
            print(f"::error file={OUT.relative_to(ROOT)}::stale — run: python3 tools/gen_data_dictionary.py", file=sys.stderr)
            return 1
        print(f"gen_data_dictionary: {OUT.relative_to(ROOT)} matches the pinned database")
        return 0
    OUT.write_text(page)
    print(f"gen_data_dictionary: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
